name: generate animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # generates a snake game from a github user (<github_user_name>) contributions graph, output a svg animation at <svg_out_path>
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/blackandwhite-dark.svg?color_snake=#2ea043&color_dots=#222,#444,#666,#888,#aaa
            dist/blackandwhite-light.svg?color_snake=#22863a&color_dots=#f5f5f5,#e0e0e0,#cfcfcf,#b0b0b0,#888
            dist/tokyonight-dark.svg?color_snake=#00c9ff&color_dots=#1f2937,#374151,#60a5fa,#a78bfa,#d1d5db
            dist/tokyonight-light.svg?color_snake=#007acc&color_dots=#f0f9ff,#bae6fd,#60a5fa,#a78bfa,#334155
            dist/theme2-dark.svg?color_snake=#38bdf8&color_dots=#0f2027,#1e3a5f,#2c5364,#94a3b8,#e2e8f0
            dist/theme2-light.svg?color_snake=#0ea5e9&color_dots=#f0f9ff,#bae6fd,#38bdf8,#0284c7,#0f172a
            dist/matrix-dark.svg?color_snake=#00ff88&color_dots=#0d0d0d,#1a1a1a,#39ff14,#6ee7b7,#d1fae5
            dist/matrix-light.svg?color_snake=#008f4c&color_dots=#f0fff4,#bbf7d0,#4ade80,#16a34a,#14532d
            dist/cyberpunk-dark.svg?color_snake=#ff2d95&color_dots=#111827,#312e81,#7c3aed,#c084fc,#f9a8d4
            dist/cyberpunk-light.svg?color_snake=#e11d48&color_dots=#fff1f2,#fbcfe8,#f472b6,#db2777,#831843
            dist/sunset-dark.svg?color_snake=#ff7b00&color_dots=#1e293b,#334155,#f97316,#facc15,#fde68a
            dist/sunset-light.svg?color_snake=#ea580c&color_dots=#fff7ed,#fed7aa,#fb923c,#ea580c,#7c2d12
            dist/mono-dark.svg?color_snake=#6b7280&color_dots=#0f172a,#334155,#64748b,#94a3b8,#e5e7eb
            dist/mono-light.svg?color_snake=#4b5563&color_dots=#f9fafb,#e5e7eb,#d1d5db,#9ca3af,#374151

      # push the content of <build_dir> to a branch
      # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}